[phases.setup]
nixPkgs = ["python3", "pip"]

[phases.install]
cmds = ["cd backend/python && pip install -r requirements.txt"]

[start]
cmd = "cd backend/python && gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
