services:
  - type: web
    name: codecade
    env: node
    region: oregon
    rootDir: backend/node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_TYPE
        value: mongodb
      - key: PORT
        fromService:
          type: web
          name: codecade
          property: port
    plan: free

